name: Deploy ProxLock to Azure

concurrency:
  group: Production
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
    build-and-deploy:
        environment:
          name: Production
          url: https://api.proxlock.dev
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
        
        - name: 'Set commit SHA in routes.swift'
          run: |
            sed -i "s|%%REPLACE_HERE_IN_CI%%|${{ github.sha }}|g" Sources/ProxLock/routes.swift
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: proxlock.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t proxlock.azurecr.io/proxlock:latest
            docker push proxlock.azurecr.io/proxlock:latest